### ISSUE TITLE
(Bitcoin) Which sign func should I use to build a transaction?

### ISSUE THREAD

**Issue by AlleniCode** [TrustWallet/trust-core#66]
There are some sign funcs in the ‘BitcoinSignerTests.swift’ file:

SignTransaction、SignP2WPKH、SignP2WSH、SignP2SH_P2WPKH、SignP2SH_P2WSH

I got UTXOs from my API, now I want to build a transaction, but I'm not clear which sign func should I use, Thx!

My UTXO data（Testnet）:
{
    "tx_hash": "6991154e998d0c6fa16427d9d214f311bde1236d8a1040d759359475bf074689",
    "tx_output_n": 0,
    "tx_version": 1,
    "tx_locktime": 0,
    "value": 1,
    "script": "a91430e0467762621877fae8d66122346adc81b9565e87",
    "addr": "2Mwhf6QjWi8MTNGGi2wqripb982fiRLwP58",
    "confirmations": 21423,
}

@hewigovens @vikmeup

**Comment by hewigovens** [comment]
it depends on your UTXO scriptPub
